name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy-deployment:
    name: Destroy Terraform Deployment Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      # Determine Branch Based On Dispatch
      - name: Determine Branch Environment & TFVARS Files
        run: |
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            BRANCH="${GITHUB_REF#refs/heads/}"
          else
            BRANCH="${{ github.event.workflow_run.head_branch }}"
          fi

          case "$BRANCH" in
            dev)
              ENV="dev"
              ;;
            staging)
              ENV="staging"
              ;;
            main)
              ENV="production"
              ;;
            *)
              echo "Invalid Target Branch: $BRANCH"
              exit 1
              ;;
          esac

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=environments/${ENV}/${ENV}.tfvars" >> $GITHUB_ENV
          echo "BACKEND_TFVARS_FILE=environments/${ENV}/backend.tfvars" >> $GITHUB_ENV

        # Set Environment Output
      - name: Set Environment Output
        id: set-env
        run: |
          echo "Environment Detected: $ENV"
          echo "env=${ENV}" >> $GITHUB_OUTPUT
          echo "tfvars_file=${TFVARS_FILE}" >> $GITHUB_OUTPUT
          echo "backend_tfvars_file=${BACKEND_TFVARS_FILE}" >> $GITHUB_OUTPUT

      # Confirm TFVARS Files Exist
      - name: Confirm TFVARS Files
        run: |
          for f in "${{ env.TFVARS_FILE }}" "${{ env.BACKEND_TFVARS_FILE }}"; do
            if [ ! -f "$f" ]; then
              echo "Unable To Find: $f"
              exit 1
            fi
            echo "Found: $f"
          done

        # Determine Branch Resouce Variables
      - name: Determine Branch Resource Variables
        run: |
          BACKEND_FILE="environments/${ENV}/backend.tfvars"

          if [ ! -f "$BACKEND_FILE" ]; then
           echo "Backend TFVARS file not found: $BACKEND_FILE"
           exit 1
          fi

           RG=$(grep -E '^resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           SA=$(grep -E '^storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           CONTAINER=$(grep -E '^storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           KEY=$(grep -E '^state_key_deployment' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)

           RG="${RG//$'\r'/}"
           SA="${SA//$'\r'/}"
           CONTAINER="${CONTAINER//$'\r'/}"
           KEY="${KEY//$'\r'/}"

           echo "RG_NAME=$RG" >> $GITHUB_ENV
           echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
           echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
           echo "STATE_KEY_DEPLOYMENT=$KEY" >> $GITHUB_ENV

        # Confirm Backend Variables
      - name: Confirm Backend Variables
        run: |
          echo "Resource Group Name       : ${{ env.RG_NAME }}"
          echo "Storage Account Name      : ${{ env.STORAGE_ACCOUNT_NAME }}"
          echo "Storage Container Name    : ${{ env.STORAGE_CONTAINER_NAME }}"
          echo "Terraform Deployment State Key       : ${{ env.STATE_KEY_DEPLOYMENT }}"

      # Clear Cahce
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform
          rm -f .terraform.lock.hcl

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete"

        # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Initialize Terraform Using Deployment State
      - name: Initialize Deployment Terraform State
        working-directory: .
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_KEY_DEPLOYMENT }}" \
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

        # Terraform Version
      - name: Terraform Version
        run: terraform version

      # Destroy Resources In Deployment
      - name: Terraform Destroy Deployment Resources
        working-directory: .
        run: |
          terraform destroy \
          -var-file="${{ env.TFVARS_FILE }}" \
          -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" \
          -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # Destroy Terraform Deployment Backend Resources
  terraform-destroy-backend:
    name: Destroy Terraform Deployment Backend Resources
    runs-on: ubuntu-latest
    needs: terraform-destroy-deployment

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Determine Branch Environment
        run: |
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
             BRANCH="${GITHUB_REF#refs/heads/}"
           else
             BRANCH="${{ github.event.workflow_run.head_branch }}"
           fi

           case "$BRANCH" in
             dev)
               ENV="dev"
               ;;
             staging)
               ENV="staging"
               ;;
             main)
               ENV="production"
               ;;
             *)
               echo "Invalid Target Branch: $BRANCH"
               exit 1
               ;;
           esac

           echo "ENV=$ENV" >> $GITHUB_ENV
           echo "TFVARS_FILE=environments/${ENV}/backend.tfvars" >> $GITHUB_ENV
           echo "Environment Detected: $ENV"
           echo "Using TFVARS File: environments/${ENV}/backend.tfvars"

        # Set Environment Output
      - name: Set Environment Output
        id: set-env
        run: |
          echo "Environment Detected: $ENV"
          echo "env=${ENV}" >> $GITHUB_OUTPUT

      # Confirm TFVARS exists
      - name: Confirm TFVARS File
        run: |
          if [ ! -f "${{ env.TFVARS_FILE }}" ]; then
            echo "Unable To Find: ${{ env.TFVARS_FILE }}"
            exit 1
          fi
          echo "Found: ${{ env.TFVARS_FILE }}"

      # Load Backend Variables
      - name: Determine Backend Variables
        run: |
          BACKEND_FILE="environments/${ENV}/backend.tfvars"
            
          if [ ! -f "$BACKEND_FILE" ]; then
           echo "Backend TFVARS file not found: $BACKEND_FILE"
           exit 1
          fi

            RG=$(grep -E '^resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
            SA=$(grep -E '^storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
            CONTAINER=$(grep -E '^storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
            KEY=$(grep -E '^state_key_backend' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)

            RG="${RG//$'\r'/}"
            SA="${SA//$'\r'/}"
            CONTAINER="${CONTAINER//$'\r'/}"
            KEY="${KEY//$'\r'/}"

            echo "RG_NAME=$RG" >> $GITHUB_ENV
            echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
            echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
            echo "STATE_KEY_BACKEND=$KEY" >> $GITHUB_ENV

      # Confirm Backend Variables
      - name: Confirm Backend Variables
        run: |
          echo "Resource Group Name       : ${{ env.RG_NAME }}"
          echo "Storage Account Name      : ${{ env.STORAGE_ACCOUNT_NAME }}"
          echo "Storage Container Name    : ${{ env.STORAGE_CONTAINER_NAME }}"
          echo "Terraform Backend State Key : ${{ env.STATE_KEY_BACKEND }}"

      # Clear Cahce
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform
          rm -f .terraform.lock.hcl

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          rm -rf environments/backend/bootstrap/.terraform
          rm -f environments/backend/bootstrap/.terraform.lock.hcl

          echo "Cleanup Complete"

        # Azure Authentication
      - name: Azure Authentication
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Break Lease
      - name: Break Terraform Backend Lease
        run: |
          az storage blob lease break \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --container-name ${{ env.STORAGE_CONTAINER_NAME }} \
            --blob-name ${{ env.STATE_KEY_BACKEND }} \
          --auth-mode login || echo "No lease present, continuing..."

        # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Initialize Terraform Using Backend State
      - name: Initialize Backend Terraform State
        working-directory: environments/backend
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_KEY_BACKEND }}" \
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Version
        run: terraform version

      # Destroy Enviroment Backend Resources
      - name: Terraform Destroy Backend
        working-directory: environments/backend
        run: |
          terraform destroy \
          -var-file=../${ENV}/backend.tfvars -auto-approve \
          -lock=false || echo "Skipping State Lock Error"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

        # Azure Authentication
      - name: Azure Authentication
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Delete RG If Any Errors From State File
      - name: Delete Backend Resource Group If Required
        shell: bash
        run: |
          set +e

          echo "Checking Resource Group Exists: $RG_NAME"
          az group show --name "$RG_NAME" > /dev/null 2>&1
              if [ $? -eq 0 ]; then
                echo "Resource Group Exists"
                az group delete \
                  --name "$RG_NAME" \
                  --yes \
                  --no-wait
                echo "Deleting $RG_NAME ..."
              else
                echo "Resource Group $RG_NAME Does Not Exist. Skipping..."
              fi

              exit 0
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
