name: Auto Update Site

on:
  push:
    branches:
      - main
    paths:
      - "Static-Site/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login To Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: List VMSS & Instances
        run: |
          echo "Discovering VMSS..."
          VMSS_LIST=$(az vmss list --query "[?tags.App=='vmss-static-site'].[name,resourceGroup]" -o tsv)

          if [ -z "$VMSS_LIST" ]; then
            echo "No VMSS found"
            exit 0
          fi

          echo "Discovered VMSS And Instances:"
          while IFS=$'\t' read -r VMSS RG; do
            echo "-------------------------------------------"
            echo "VMSS: $VMSS (Resource Group: $RG)"
            az vmss list-instances --resource-group "$RG" --name "$VMSS" \
              --query "[].{InstanceID:instanceId, Name:computerName, State:provisioningState}" \
              -o table
          done <<< "$VMSS_LIST"

      - name: Discover VMSS And Update
        run: |
          set -e
          LOG_FILE="/tmp/vmss_update.log"
          echo "=== Deployment started: $(date) ===" > "$LOG_FILE"

          # Get all VMSS with tag App=vmss-static-site
          VMSS_LIST=$(az vmss list \
            --query "[?tags.App=='vmss-static-site'].[name,resourceGroup]" \
            -o tsv)

          if [ -z "$VMSS_LIST" ]; then
            echo "No VMSS found" | tee -a "$LOG_FILE"
            exit 1
          fi

          # Loop over each VMSS
          while IFS=$'\t' read -r VMSS RG; do
            echo "Deploying to VMSS: $VMSS (RG: $RG)" | tee -a "$LOG_FILE"

            # Get all instance IDs
            INSTANCE_IDS=$(az vmss list-instances --resource-group "$RG" --name "$VMSS" --query "[].instanceId" -o tsv)

            for ID in $INSTANCE_IDS; do
              echo "Running update on instance $ID of $VMSS" | tee -a "$LOG_FILE"

              az vmss run-command invoke \
                --resource-group "$RG" \
                --name "$VMSS" \
                --instance-id "$ID" \
                --command-id RunShellScript \
                --scripts "curl -sSL https://raw.githubusercontent.com/Jammy-1/Azure-VMSS-Web-Multi-Region-MultiAZ/main/Modules/Scripts/update_site.sh | bash" \
                | tee -a "$LOG_FILE"

              if [ "${PIPESTATUS[0]}" -ne 0 ]; then
                echo "Deployment failed on $VMSS instance $ID" | tee -a "$LOG_FILE"
                exit 1
              else
                echo "Deployment succeeded on $VMSS instance $ID" | tee -a "$LOG_FILE"
              fi
            done

          done <<< "$VMSS_LIST"

          echo "=== Deployment finished: $(date) ===" | tee -a "$LOG_FILE"
